/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace BubbleCouple
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ClockSync : TBase
  {
    private int _step;
    private long _clientTime;
    private long _serverTime;
    private long _delta;

    public int Step
    {
      get
      {
        return _step;
      }
      set
      {
        __isset.step = true;
        this._step = value;
      }
    }

    public long ClientTime
    {
      get
      {
        return _clientTime;
      }
      set
      {
        __isset.clientTime = true;
        this._clientTime = value;
      }
    }

    public long ServerTime
    {
      get
      {
        return _serverTime;
      }
      set
      {
        __isset.serverTime = true;
        this._serverTime = value;
      }
    }

    public long Delta
    {
      get
      {
        return _delta;
      }
      set
      {
        __isset.delta = true;
        this._delta = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool step;
      public bool clientTime;
      public bool serverTime;
      public bool delta;
    }

    public ClockSync() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.I32) {
                Step = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.I64) {
                ClientTime = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 30:
              if (field.Type == TType.I64) {
                ServerTime = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 40:
              if (field.Type == TType.I64) {
                Delta = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ClockSync");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.step) {
          field.Name = "step";
          field.Type = TType.I32;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Step);
          oprot.WriteFieldEnd();
        }
        if (__isset.clientTime) {
          field.Name = "clientTime";
          field.Type = TType.I64;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(ClientTime);
          oprot.WriteFieldEnd();
        }
        if (__isset.serverTime) {
          field.Name = "serverTime";
          field.Type = TType.I64;
          field.ID = 30;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(ServerTime);
          oprot.WriteFieldEnd();
        }
        if (__isset.delta) {
          field.Name = "delta";
          field.Type = TType.I64;
          field.ID = 40;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(Delta);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ClockSync(");
      bool __first = true;
      if (__isset.step) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Step: ");
        __sb.Append(Step);
      }
      if (__isset.clientTime) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ClientTime: ");
        __sb.Append(ClientTime);
      }
      if (__isset.serverTime) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ServerTime: ");
        __sb.Append(ServerTime);
      }
      if (__isset.delta) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Delta: ");
        __sb.Append(Delta);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
