/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace BubbleCouple
{
  public enum EBattleCommandType
  {
    CmdFireBall = 1,
    CmdFireBallResponse = 2,
    CmdEraseBall = 3,
    CmdFallBall = 4,
    CmdExchangeBall = 5,
    CmdBallQueue = 6,
    CmdSceneTransform = 7,
  }
}
