/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace BubbleCouple
{
  public enum JoinGameResult
  {
    JGR_Success = 0,
    JGR_UserFull = 1,
    JGR_BattleFull = 2,
    JGR_AlreadyInBattle = 3,
  }
}
