/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace BubbleCouple
{
  public enum MessageId
  {
    CS_EnterGame = 420282369,
    SC_EnterGame = 437059585,
    CS_StartLevel = 420282370,
    SC_StartLevel = 437059586,
    SC_EndBattle = 437059587,
    CS_BattleCommand = 420282372,
    SC_BattleCommand = 437059588,
    CS_ResetServer = 420282373,
    SC_ResetServer = 437059589,
    SC_MatchSuccess = 437059590,
    CS_ClockSync = 420282375,
    SC_ClockSync = 437059591,
    CS_StartBattle = 420282376,
    SC_StartBattle = 437059592,
    CS_LeaveLevel = 420282377,
    SC_LeaveLevel = 437059593,
    CS_LeaveGame = 420282378,
    SC_LeaveGame = 437059594,
    CS_JoinGame = 420282401,
    SC_JoinGame = 437059617,
  }
}
